development:
 adapter: postgresql
 database: hashtag-viper
 username: <%= ENV['PG_USER'] %>
 password: <%= ENV['PG_PASS'] %>
 host: localhost

production:
 adapter: postgresql
 database: hashtag-viper
 username: <%= ENV['PG_USER'] %>
 password: <%= ENV['PG_PASS'] %>
 host: <%= ENV['HEROKU_POSTGRESQL_COPPER_URL'] %>